logging:
  file:
    name: ${user.dir}/log/test.log  # ?? ?? ????.
    max-history: 7 # ?? ?? ?? ????. 7? ?? ??? ????.
    max-size: 10MB  # ?? ?? ??? ?? ?? ?????.
  level:  # ? package ?? ?? ??? ??? ? ??.
    com.project.study : error
    com.project.study.controller : debug